name: pd-actions

on:
    schedule:
      - cron: '0 0 * * *'
# Remove both comments to run this action on daily basis.
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev # Required for Naabu

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up ProjectDiscovery tools
        if: steps.cache-go.outputs.cache-hit != 'true'
        env:
          GO111MODULE: on
        run: |
          go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder
          go get -v github.com/projectdiscovery/dnsx/cmd/dnsx
          go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu
          go get -v github.com/projectdiscovery/httpx/cmd/httpx
          go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
          go get -v github.com/projectdiscovery/notify/cmd/notify
#          go get -v github.com/projectdiscovery/cloudlist/cmd/cloudlist
        shell: bash

      - name: Running SubFinder for passive DNS enumeration
        run: |
          subfinder -dL input/domains.txt -config config/subfinder-config.yaml -o output4/passive_subdomains.txt
        shell: bash

      - name: Running dnsx for valid DNS filtering 
        run: |
          dnsx -l output4/passive_subdomains.txt -t 50 | tee output4/active_subdomains.txt
        shell: bash

      - name: Running naabu to check top 100 ports
        run: |
          naabu -iL output4/active_subdomains.txt  -rate 10000 -top-ports 100 | tee output4/active_ports.txt
        shell: bash

#      For running vulnerability assessment of cloud assets.
#      - name: Enumerating hosts from Cloud with Cloudlist
#        run: |
#          cloudlist -config config/cloudlist-config.yaml -ip | tee output/cloud_hosts.txt >> output/active_ports.txt
#        shell: bash

      - name: Running httpx for HTTP webservers probbing
        run: |
          httpx -l output4/active_ports.txt | tee output4/active_urls.txt
        shell: bash

      - name: Nuclei Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: output4/active_urls.txt
          output: output4/nuclei_output.txt
          
      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output4/passive_subdomains.txt
          git add output4/active_subdomains.txt
          git add output4/active_ports.txt
          git add output4/active_urls.txt
          git add output4/nuclei_output.txt
#          git add output/cloud_hosts.txt

      - name: Commit results to Github
        run: |
          git config --local user.email "18it036.parth.manek@vvpedulink.ac.in"
          git config --global user.name "SuBZer0-cpu"
          git commit -m "PD-Actions report" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
